lib/noble_web/router.ex
defmodule NobleWeb.Router do
  use NobleWeb, :router
  require Ueberauth
  require Logger

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NobleWeb.Plugs.Locale
    plug :session_to_assigns
    plug :put_user_token
    plug :protect_access
  end

  pipeline :authenticated do
    plug :secure
  end

  pipeline :protect_access do
    plug :require_header
  end

  scope "/", NobleWeb do
    pipe_through [:browser, :authenticated]
  end

  scope "/", NobleWeb do
    pipe_through :browser

    get "/", HomeController, :index

    get "/logout", AuthController, :logout
  end

  scope "/legal", NobleWeb do
    pipe_through :browser

    get "/:doc", LegalController, :index
  end

  scope "/auth", NobleWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    post "/logout", AuthController, :delete
  end

  defp session_to_assigns(conn, _params) do
    user = get_session(conn, :current_user)

    conn
    |> assign(:current_user, user)
  end

  defp secure(conn, _params) do
    user = get_session(conn, :current_user)

    case user do
      nil ->
        conn |> redirect(to: "/auth/auth0") |> halt

      _ ->
        conn
        |> assign(:current_user, user)
    end
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      salt = Application.get_env(:noble, NobleWeb.Endpoint)[:secret_key_base]
      token = Phoenix.Token.sign(conn, salt, current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp require_header(conn, _) do
    if conn.host =~ "gigalixirapp.com" do
      case(get_req_header(conn, "x-allow-access")) do
        [allow_access] when allow_access == "true" ->
          conn

        _ ->
          Logger.info(
            "A request from " <>
              to_string(:inet_parse.ntoa(conn.remote_ip)) <> " has no x-allow-access header"
          )

          conn |> redirect(to: "/") |> halt()
      end
    else
      conn
    end
  end
end

lib/noble_web/views/layout_view.ex
defmodule NobleWeb.LayoutView do
  use NobleWeb, :view

  def top_navigation do
    "top_navigation.html"
  end

  def drawer_menu do
    "drawer_menu.html"
  end
end

lib/noble_web/templates/layout/app.html.eex
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Noble</title>

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Page styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.min.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>

    <%= if !String.contains?(Phoenix.Controller.current_url(@conn), "localhost") do %>
    <script type="text/javascript">
        window.smartlook||(function(d) {
        var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName('head')[0];
        var c=d.createElement('script');o.api=new Array();c.async=true;c.type='text/javascript';
        c.charset='utf-8';c.src='https://rec.smartlook.com/recorder.js';h.appendChild(c);
        })(document);
        smartlook('init', 'b676128fe66a34c71d08c926874ffec0d121000f');
    </script>
    <% end %>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <%= render @view_module, @view_template, Map.put(assigns, :layout, {NobleWeb.LayoutView, top_navigation()}) %>
    <%= render @view_module, @view_template, Map.put(assigns, :layout, {NobleWeb.LayoutView, drawer_menu()}) %>
      <div class="and-content mdl-layout__content">
        <a name="top"></a>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <%= csrf_meta_tag() %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/noble_web/templates/layout/drawer_menu.html.eex
      <div class="android-drawer mdl-layout__drawer">
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href=""><i class="material-icons">sports_esports</i>&nbsp &nbsp <%= gettext "Games" %></a>
          <div class="and-drawer-separator"></div>
          <%= if @current_user do %>
            <div class="mdl-navigation__link" href=""><i class="material-icons">account_balance</i>&nbsp &nbsp <%= gettext "Sold items" %></div>
            <a class="mdl-navigation__link" href="<%= Routes.auth_path(@conn, :logout) %>"><i class="material-icons">exit_to_app</i>&nbsp &nbsp <%= gettext "Sign out" %></a>
          <% else %>
            <a class="mdl-navigation__link" href="<%= Routes.auth_path(@conn, :request, :auth0) %>"><i class="material-icons">account_box</i>&nbsp &nbsp <%= gettext "Sign in / Sign up" %></a>
          <% end %>
          <div class="and-drawer-separator"></div>
          <div class="mdl-navigation__link"><i class="material-icons">help_outline</i>&nbsp &nbsp <%= gettext "How it works" %></div>
          <a class="mdl-navigation__link" href="<%= Routes.legal_path(@conn, :index, :terms) %>"><i class="material-icons">menu_book</i>&nbsp &nbsp <%= gettext "Terms & Conditions" %></a>
          <a class="mdl-navigation__link" href="<%= Routes.legal_path(@conn, :index, :privacy_notice) %>"><i class="material-icons">policy</i>&nbsp &nbsp <%= gettext "Privacy Notice" %></a>
          <a class="mdl-navigation__link" href="<%= Routes.legal_path(@conn, :index, :disclaimer) %>"><i class="material-icons">info</i>&nbsp &nbsp <%= gettext "Disclaimer" %></a>
          <div class="and-drawer-separator"></div>
        </nav>
      </div>

lib/noble_web/templates/layout/top_navigation.html.eex
      <div class="and-header mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
          <span class="and-title mdl-layout-title">
            <a href="/"><img class="and-logo-image" src="<%= Routes.static_path(@conn, "/images/logo.svg") %>"></a>
          </span>
          <!-- Add spacer, to align navigation to the right in desktop -->
          <div class="and-header-spacer mdl-layout-spacer"></div>
          <div class="and-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search-field">
            </div>
          </div>
          <!-- Navigation -->
          <div class="and-navigation-container">
            <nav class="and-navigation mdl-navigation">
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href=""><%= gettext "How it works" %></a>
            </nav>
          </div>
          <span class="and-mobile-title mdl-layout-title">
            <img class="and-logo-image" src="<%= Routes.static_path(@conn, "/images/logo.svg") %>">
          </span>
          <%= if @current_user do %>
            <button class="and-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
              <li disabled class="mdl-menu__item"><%= @current_user.name %></li>
              <div class="and-drawer-separator"></div>
              <li class="mdl-menu__item"><%= Phoenix.HTML.Link.link gettext("Sign out"), to: Routes.auth_path(@conn, :logout), class: "menu_link"%></li>
          </ul>
          <% else %>
            <button class="and-more-button mdl-button mdl-js-button" id="login">
              <%= Phoenix.HTML.Link.link gettext("Sign in / Sign up"), to: Routes.auth_path(@conn, :request, :auth0) %>
            </button>
          <% end %>
        </div>
      </div>